### ISSUE TITLE
opensips-cli add user failed, unsupported hash type sha512-256

### ISSUE THREAD

**Issue by fangang1989** [OpenSIPS/opensips-cli#109]
when i add a new user by opensips-cli , but it can not add successfully, and more info as follows:

[root@vmsOMiFfWXtutLxt3b opensips]# opensips-cli -x user add fg001@test.com fg001
DEBUG: fifo file /tmp/opensips_fifo does not exist!
DEBUG: Loaded module 'user'
DEBUG: running in non-interactive mode user add ['fg001@test.com', 'fg001']
DEBUG: running command 'add' '['fg001@test.com', 'fg001']'
DEBUG: connecting to mysql://opensips:opensipsrw@localhost
Traceback (most recent call last):
  File "/usr/lib64/python3.6/hashlib.py", line 178, in __hash_new
    name, data, usedforsecurity=usedforsecurity)
ValueError: unsupported hash type sha512-256

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/bin/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/lib/python3.6/site-packages/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 247, in cmdloop
    ret = self.run_command(module, command, modifiers, params)
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 409, in run_command
    return mod[0].__invoke__(cmd, params, modifiers)
  File "/usr/lib/python3.6/site-packages/opensipscli/module.py", line 36, in __invoke__
    return f(params, modifiers)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/user.py", line 168, in do_add
    self.user_get_ha1_sha512t256(username, domain, password)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/user.py", line 119, in user_get_ha1_sha512t256
    o = hashlib.new("sha512-256")
  File "/usr/lib64/python3.6/hashlib.py", line 189, in __hash_new
    return __get_builtin_constructor(name)(data, **kwargs)
  File "/usr/lib64/python3.6/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512-256

my computer info is:
os version: CentOS 7.9
python version:3.6.8
opensips-cli vesion: 0.2.0

please help me ,how to solve the problme？ thanks.

**Comment by gao114882** [comment]
this issue i met,  update python to 3.9.18

**Comment by liviuchircu** [comment]
PS: I just realized CentOS 7.9 is not the new generation of "CentOS Stream" (that starts at `8`, now at `9`).  So we're talking about a vanilla CentOS, which we can reasonably expect to have an older than 1.1.1 OpenSSL too!

**Comment by liviuchircu** [comment]
Added handling for this exception in e3ec055f15a.
