### ISSUE TITLE
opensips-cli cannot start w/o SQLAlchemy

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips-cli#17]
The recent Postgres PR has introduced a regression, where the CLI is no longer able to run without SQLAlchemy installed.  Previously, it would work and simply not provide the `database` module at all.  To reproduce:

```
diff --git a/setup.py b/setup.py
index 3f0e1d7..7b7facd 100644
--- a/setup.py
+++ b/setup.py
@@ -64,8 +64,6 @@ setup(
     ],
     install_requires=[
         'mysqlclient<1.4.0rc1',
-        'sqlalchemy==1.3.3',
-        'sqlalchemy-utils'
     ],
     classifiers = [
         "Programming Language :: Python :: 3",
```

and install it again.  Now, when running `opensips-cli`, we get:

```
Traceback (most recent call last):
  File "/usr/local/bin/opensips-cli", line 4, in <module>
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/opensipscli-0.1-py3.6.egg/EGG-INFO/scripts/opensips-cli", line 3, in <module>
    from opensipscli import main
  File "/home/liviu/src/opensips-cli/opensipscli/main.py", line 22, in <module>
    from opensipscli import cli, defaults
  File "/home/liviu/src/opensips-cli/opensipscli/cli.py", line 31, in <module>
    from opensipscli.modules import *
  File "/home/liviu/src/opensips-cli/opensipscli/modules/__init__.py", line 24, in <module>
    __import__(modname)
  File "/home/liviu/src/opensips-cli/opensipscli/modules/database.py", line 23, in <module>
    from opensipscli.db import (
  File "/home/liviu/src/opensips-cli/opensipscli/db.py", line 38, in <module>
    Base = declarative_base()
NameError: name 'declarative_base' is not defined
```

Reported by @danpascu

**Comment by razvancrainea** [comment]
This have been fixed in 52e4d5f9399955433f84a27386eaacc6573076ca
