### ISSUE TITLE
'database create/add' do not work with PostgreSQL

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips-cli#23]
```
Create [a]ll tables or just the [c]urrently configured ones? (Default value is a):
Creating all tables ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
psycopg2.InternalError: CREATE DATABASE cannot run inside a transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/opensips-cli", line 4, in <module>
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/EGG-INFO/scripts/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/EGG-INFO/scripts/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/cli.py", line 199, in cmdloop
    ret = self.run_command(self.command[0], command, params)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/cli.py", line 293, in run_command
    return mod[0].__invoke__(cmd, params)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/module.py", line 30, in __invoke__
    return f(params)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/modules/database.py", line 243, in do_create
    self._do_create(db)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/modules/database.py", line 298, in _do_create
    db.create(db_name)
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1-py3.6.egg/opensipscli/db.py", line 138, in create
    self.__conn.execute("CREATE DATABASE {}".format(db_name))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 982, in execute
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1155, in _execute_text
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
sqlalchemy.exc.InternalError: (psycopg2.InternalError) CREATE DATABASE cannot run inside a transaction block

[SQL: CREATE DATABASE opensips]
(Background on this error at: http://sqlalche.me/e/2j85)
```

Reported by @acheraime [here](https://github.com/OpenSIPS/opensips-cli/issues/13#issuecomment-501529243).

The problem seems to be that the PGSQL support has a separate set of sub-commands, namely `create_db` (instead of the already existing `create`) and `create_module` (instead of the already existing `add`).  This creates confusion for users, since it's hard to know which sub-command to call for each backend: "should I call `database create` or `database create_db`?"

I suggest we merge these duplicate commands into a solution that works for any backend, regardless of how you invoke it from the console.

**Comment by AntonescuAlexandru** [comment]
I cannot reproduce the problem on centos 6.9 or xubuntu 18.04.

**Comment by lminiero** [comment]
Not sure if this is the issue to refer to (especially considering #13, which I shared many errors with, has been closed), but I'm unable to create a database on PostgreSQL as well. Not sure if this can be caused by the fact Fedora comes with Python 3.7, and I've seen older versions mentioned in pretty much all other issues.

The first attempts with an existing user I have, I'd get weird errors like this:

```
(opensips-cli): database create  
Please provide the URL of the SQL database: postgres://lminiero:test@localhost
ERROR: cannot connect to DB server: (psycopg2.OperationalError) FATAL:  database "lminiero" does not exist
```

This is a bit surprising, since the documentation says that it's the url is in the `backend://user:pass@hostname` form, and the default database is `opensips`, but apparenty the `user` part is used instead. Using `localhost/opensips` seems to tell `opensips-cli` to use `opensips` as a database instead, so the documentation should probably reflect that.

That said, I'm in a weird situation where I get two different, and contradicting, errors. If the `opensips` database doesn't exist (which is what I assumed would be the default), I get this error:

```
[lminiero@lminiero opensips-cli] $ opensips-cli -x database create
Please provide the URL of the SQL database: postgres://lminiero:ietf@localhost/opensips
ERROR: cannot connect to DB server: (psycopg2.OperationalError) FATAL:  database "opensips" does not exist
```

If I manually create the database and try again, though, I get this:

```
[lminiero@lminiero ~] $ sudo -u postgres createdb -O opensips opensips
[lminiero@lminiero opensips-cli] $ opensips-cli -x database create
Please provide the URL of the SQL database: postgres://lminiero:ietf@localhost/opensips
WARNING: database 'opensips' already exists!
```

The warning is weird by itself, since it seems to contradict the previous error. It also seems to suggest something happened anyway, which didn't though, because no tables are created:

```
opensips-> \d
Did not find any relations.
```

Any hint on what I can do to fix this issue? Is PostgreSQL indeed known not to work, and should I switch to MySQL/MariaSQL instead? Thanks!

PS: while Opensips (3.0.2) and many of its modules are available in the Fedora repos, `opensips-cli` isn't: not sure who maintains the packages there, but it may be worthwhile to prepare an rpm for that too, as otherwise I suspect there are no ways to configure/control an instance (apologies if I'm mistaken, I'm a n00b :smile: )

**Comment by liviuchircu** [comment]
Ok, I am raising the priority of this issue now.  It's time to make the `database` module consistent and well-tested again across multiple backends.  And, *no*, @lminiero, you should absolutely not switch to MySQL/Maria!

**Comment by lminiero** [comment]
> And, _no_, @lminiero, you should absolutely not switch to MySQL/Maria!

I've been using it these past few days for a few simple tests and it seems to be working fine, but I'll be happy to jump to PostgreSQL when I can get it to work. Thanks for looking into it!

**Comment by liviuchircu** [comment]
Also, in the meantime: for PostgreSQL, just don't use the problematic `database create` command, and use `database create_db` instead, which seems to have been created specifically for Postgres (and works, too!).  The idea of this issue is to get rid of `create_db` and merge it into the `create` command!

**Comment by lminiero** [comment]
I forgot to mention that, but I actually tried that already as part of my tests, and the result was the same :disappointed:  Notice this may also be because Fedora ships a quite recent version of Postgres too (11.6), so not sure if there were breaking changes in that sense.

**Comment by liviuchircu** [comment]
@lminiero I managed to merge the PostgreSQL support into the `database create/add/drop` commands.  Additionally, the `database` module should require zero configuration (if you use MySQL, of course) and it should be very friendly.  Please pull the latest version (or install tomorrow's nightly packages) and let me know if it plays nicer now.

If there are any issues, I suggest we take care of them in a new ticket.  Many thanks!

**Comment by lminiero** [comment]
@liviuchircu thanks! I'll give it a try and open a new issue in case.
