### ISSUE TITLE
Error during opensips-cli installation and execution

### ISSUE THREAD

**Issue by abdoulosseni** [OpenSIPS/opensips-cli#4]
Hello,
Try to install opensip-cli but something wrong
`byte-compiling build/bdist.linux-x86_64/egg/opensipscli/cli.py to cli.pyc
  File "build/bdist.linux-x86_64/egg/opensipscli/cli.py", line 309
    print(num, line, end='')
                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/opensipscli/db.py to db.pyc
  File "build/bdist.linux-x86_64/egg/opensipscli/db.py", line 61
    raise osdbError("unable to connect to the database") from None
                                                            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/opensipscli/defaults.py to defaults.pyc`

Then, when I excecute opensips-cli, I got errors:

`root@pstn-2:~/opensips-cli# opensips-cli
Traceback (most recent call last):
  File "/usr/local/bin/opensips-cli", line 4, in <module>
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/opensips-cli' not found in metadata at None
root@pstn-2:~/opensips-cli#
`
Regards

**Comment by abdoulosseni** [comment]
works well with python3.
Regards
