### ISSUE TITLE
Location and ACC Tables fail

### ISSUE THREAD

**Issue by gtanetwork** [OpenSIPS/opensips-cli#51]
Thank you for the previous fix.  The migration works with an exception of 2 tables now (not sure if this SQL structure issue in my db).

Logs are as follows: 

opensips-cli -d -x database drop
DEBUG: using config file /etc/opensips/opensips-cli.cfg
DEBUG: Loaded module 'database'
DEBUG: Loaded module 'diagnose'
DEBUG: Loaded module 'instance'
DEBUG: fifo file /tmp/opensips_fifo does not exist!
DEBUG: Skipping module 'mi' - excluded on purpose
DEBUG: Loaded module 'tls'
DEBUG: Loaded module 'trace'
DEBUG: Skipping module 'trap' - excluded on purpose
DEBUG: Loaded module 'user'
DEBUG: running in non-interactive mode '['database', 'drop']'
DEBUG: running command 'drop' '[]'
DEBUG: admin DB URL: 'mysql://root:test@localhost'
DEBUG: connecting to mysql://root:test@localhost
DEBUG: check database URL 'mysql://root:test@localhost/opensips'
DEBUG: DB 'opensips' exists
DEBUG: database 'opensips' dropped
INFO: database 'opensips' dropped!
[root@kam-outside1-lab opensips-cli.bk]# opensips-cli -d -x database migrate opensips_24 opensips
DEBUG: using config file /etc/opensips/opensips-cli.cfg
DEBUG: Loaded module 'database'
DEBUG: Loaded module 'diagnose'
DEBUG: Loaded module 'instance'
DEBUG: fifo file /tmp/opensips_fifo does not exist!
DEBUG: Skipping module 'mi' - excluded on purpose
DEBUG: Loaded module 'tls'
DEBUG: Loaded module 'trace'
DEBUG: Skipping module 'trap' - excluded on purpose
DEBUG: Loaded module 'user'
DEBUG: running in non-interactive mode '['database', 'migrate', 'opensips_24', 'opensips']'
DEBUG: running command 'migrate' '['opensips_24', 'opensips']'
DEBUG: admin DB URL: 'mysql://root:test@localhost'
DEBUG: connecting to mysql://root:test@localhost
DEBUG: check database URL 'mysql://root:test@localhost/opensips_24'
DEBUG: DB 'opensips_24' exists
Creating database opensips...
DEBUG: check database URL 'mysql://root:test@localhost/opensips'
DEBUG: DB does not exist
DEBUG: Create Database 'opensips' for dialect 'mysql' ...
DEBUG: success
DEBUG: connecting to mysql://root:test@localhost/opensips
DEBUG: check database URL 'mysql://root:test@localhost/opensips'
DEBUG: DB 'opensips' exists
DEBUG: Creating all tables
DEBUG: checking tables: usrloc alias_db tls_mgm presence avpops domain rtpproxy permissions fraud_detection userblacklist registrant smpp call_center freeswitch_scripting carrierroute closeddial domainpolicy load_balancer emergency tracer cpl speeddial clusterer dispatcher rtpengine dialog dialplan auth_db group msilo acc rls standard b2b_sca imc drouting cachedb_sql b2b
INFO: Running standard-create.sql...
INFO: Running usrloc-create.sql...
INFO: Running alias_db-create.sql...
INFO: Running tls_mgm-create.sql...
INFO: Running presence-create.sql...
INFO: Running avpops-create.sql...
INFO: Running domain-create.sql...
INFO: Running rtpproxy-create.sql...
INFO: Running permissions-create.sql...
INFO: Running fraud_detection-create.sql...
INFO: Running userblacklist-create.sql...
INFO: Running registrant-create.sql...
INFO: Running smpp-create.sql...
INFO: Running call_center-create.sql...
INFO: Running freeswitch_scripting-create.sql...
INFO: Running carrierroute-create.sql...
INFO: Running closeddial-create.sql...
INFO: Running domainpolicy-create.sql...
INFO: Running load_balancer-create.sql...
INFO: Running emergency-create.sql...
INFO: Running tracer-create.sql...
INFO: Running cpl-create.sql...
INFO: Running speeddial-create.sql...
INFO: Running clusterer-create.sql...
INFO: Running dispatcher-create.sql...
INFO: Running rtpengine-create.sql...
INFO: Running dialog-create.sql...
INFO: Running dialplan-create.sql...
INFO: Running auth_db-create.sql...
INFO: Running group-create.sql...
INFO: Running msilo-create.sql...
INFO: Running acc-create.sql...
INFO: Running rls-create.sql...
INFO: Running b2b_sca-create.sql...
INFO: Running imc-create.sql...
INFO: Running drouting-create.sql...
INFO: Running cachedb_sql-create.sql...
INFO: Running b2b-create.sql...
DEBUG: migration scripts for ['/usr/share/opensips/mysql/table-migrate.sql', '/usr/share/opensips/mysql/db-migrate.sql']
Migrating all matching OpenSIPS tables...
DEBUG: Importing /usr/share/opensips/mysql/table-migrate.sql...
DEBUG: Importing /usr/share/opensips/mysql/db-migrate.sql...
INFO: Migrating registrant data...
INFO: Migrating tls_mgm data...
ERROR: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'domain' in 'field list'")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'tls_mgm')]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'domain' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/db.py", line 715, in migrate
    old_db, old_db, new_db, tb)))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'domain' in 'field list'")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'tls_mgm')]
(Background on this error at: http://sqlalche.me/e/e3q8)
ERROR: Failed to migrate 'tls_mgm' table data, see above errors!
INFO: Migrating acc data...
ERROR: (_mysql_exceptions.OperationalError) (1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'acc')]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1136, "Column count doesn't match value count at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/db.py", line 715, in migrate
    old_db, old_db, new_db, tb)))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'acc')]
(Background on this error at: http://sqlalche.me/e/e3q8)
ERROR: Failed to migrate 'acc' table data, see above errors!
INFO: Migrating address data...
INFO: Migrating cachedb data...
INFO: Migrating carrierfailureroute data...
INFO: Migrating carrierroute data...
INFO: Migrating cc_agents data...
INFO: Migrating cc_calls data...
INFO: Migrating cc_cdrs data...
INFO: Migrating cc_flows data...
INFO: Migrating closeddial data...
INFO: Migrating clusterer data...
INFO: Migrating cpl data...
INFO: Migrating dbaliases data...
INFO: Migrating dialplan data...
INFO: Migrating dispatcher data...
INFO: Migrating domain data...
INFO: Migrating domainpolicy data...
INFO: Migrating dr_carriers data...
INFO: Migrating dr_gateways data...
INFO: Migrating dr_groups data...
INFO: Migrating dr_partitions data...
INFO: Migrating dr_rules data...
INFO: Migrating emergency_report data...
INFO: Migrating emergency_routing data...
INFO: Migrating emergency_service_provider data...
INFO: Migrating fraud_detection data...
INFO: Migrating freeswitch data...
INFO: Migrating globalblacklist data...
INFO: Migrating grp data...
INFO: Migrating imc_members data...
INFO: Migrating imc_rooms data...
INFO: Migrating load_balancer data...
INFO: Migrating location data...
ERROR: (_mysql_exceptions.OperationalError) (1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'location')]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1136, "Column count doesn't match value count at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/db.py", line 715, in migrate
    old_db, old_db, new_db, tb)))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.3-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips_24.OSIPS_TB_COPY_2_4_TO_3_0('opensips_24', 'opensips', 'location')]
(Background on this error at: http://sqlalche.me/e/e3q8)
ERROR: Failed to migrate 'location' table data, see above errors!
INFO: Migrating missed_calls data...
INFO: Migrating presentity data...
INFO: Migrating pua data...
INFO: Migrating re_grp data...
INFO: Migrating rls_presentity data...
INFO: Migrating rls_watchers data...
INFO: Migrating route_tree data...
INFO: Migrating rtpengine data...
INFO: Migrating rtpproxy_sockets data...
INFO: Migrating silo data...
INFO: Migrating sip_trace data...
INFO: Migrating smpp data...
INFO: Migrating speed_dial data...
INFO: Migrating subscriber data...
INFO: Migrating uri data...
INFO: Migrating userblacklist data...
INFO: Migrating usr_preferences data...
INFO: Migrating xcap data...
Finished copying OpenSIPS table data into database 'opensips'!

24 version DB tables are as follows: 

MariaDB [opensips_24]> describe acc;
+-------------+------------------+------+-----+---------+----------------+
| Field       | Type             | Null | Key | Default | Extra          |
+-------------+------------------+------+-----+---------+----------------+
| id          | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| method      | char(16)         | NO   |     |         |                |
| from_tag    | char(64)         | NO   |     |         |                |
| to_tag      | char(64)         | NO   |     |         |                |
| callid      | char(64)         | NO   | MUL |         |                |
| sip_code    | char(3)          | NO   |     |         |                |
| sip_reason  | char(32)         | NO   |     |         |                |
| time        | datetime         | NO   |     | NULL    |                |
| duration    | int(11) unsigned | NO   |     | 0       |                |
| ms_duration | int(11) unsigned | NO   |     | 0       |                |
| setuptime   | int(11) unsigned | NO   |     | 0       |                |
| created     | datetime         | YES  |     | NULL    |                |
| dest        | varchar(35)      | YES  |     | NULL    |                |
| clid        | varchar(35)      | YES  |     | NULL    |                |
| src_ip      | varchar(25)      | YES  |     | NULL    |                |
| drt_gw      | varchar(5)       | YES  |     | NULL    |                |
| drt_carrier | varchar(5)       | YES  |     | NULL    |                |
+-------------+------------------+------+-----+---------+----------------+
17 rows in set (0.00 sec)

MariaDB [opensips_24]> describe location;
+---------------+---------------------+------+-----+---------------------+----------------+
| Field         | Type                | Null | Key | Default             | Extra          |
+---------------+---------------------+------+-----+---------------------+----------------+
| contact_id    | bigint(10) unsigned | NO   | PRI | NULL                | auto_increment |
| username      | char(64)            | NO   |     |                     |                |
| domain        | char(64)            | YES  |     | NULL                |                |
| contact       | char(255)           | NO   |     |                     |                |
| received      | char(128)           | YES  |     | NULL                |                |
| path          | char(255)           | YES  |     | NULL                |                |
| expires       | datetime            | NO   |     | 2020-05-28 21:32:15 |                |
| q             | float(10,2)         | NO   |     | 1.00                |                |
| callid        | char(255)           | NO   |     | Default-Call-ID     |                |
| cseq          | int(11)             | NO   |     | 13                  |                |
| last_modified | datetime            | NO   |     | 1900-01-01 00:00:01 |                |
| flags         | int(11)             | NO   |     | 0                   |                |
| cflags        | char(255)           | YES  |     | NULL                |                |
| user_agent    | char(255)           | NO   |     |                     |                |
| socket        | char(64)            | YES  |     | NULL                |                |
| methods       | int(11)             | YES  |     | NULL                |                |
| sip_instance  | char(255)           | YES  |     | NULL                |                |
| attr          | char(255)           | YES  |     | NULL                |                |
+---------------+---------------------+------+-----+---------------------+----------------+
18 rows in set (0.01 sec)

MariaDB [opensips_24]>

**Comment by liviuchircu** [comment]
What OpenSIPS version are you migrating to?  I suspect this is caused by migrating to a `3.1` DB, since the migration scripts are currently meant to migrate from `2.4` to `3.0`.

**Comment by gtanetwork** [comment]
3.0.2

**Comment by liviuchircu** [comment]
Your `acc` table contains custom columns, so it cannot be migrated by the `database migrate` command.  You will have to manually extend the 3.0 table and migrate the data.

For the `location` table, it seems you're missing the `kv_store` column (this column could only useful if you were using mid-registrar).  So on your `opensips_24` database, you could just do:

    ALTER TABLE location ADD kv_store TEXT(512) DEFAULT NULL AFTER sip_instance;

then retry the migration.
